-- MySQL Script adapted from MySQL script generated by MySQL Workbench
-- Tue Feb  6 19:13:39 2024
-- Adaptation from MySQL Workbench Forward Engineering, Avni Gharpurey and Michelino Gali

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

/* Table `Vendors` */

DROP TABLE IF EXISTS `Vendors` ;

CREATE TABLE IF NOT EXISTS `Vendors` (
  `vendor_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(100) NOT NULL,
  `vendor_start_date` DATE NOT NULL,
  PRIMARY KEY (`vendor_id`));


/* Table `Categories` */

DROP TABLE IF EXISTS `Categories` ;

CREATE TABLE IF NOT EXISTS `Categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`));

/* Table `Departments` */

DROP TABLE IF EXISTS `Departments` ;

CREATE TABLE IF NOT EXISTS `Departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`department_id`));


/* Table `Products` */

DROP TABLE IF EXISTS `Products` ;

CREATE TABLE IF NOT EXISTS `Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_count` INT NULL DEFAULT 0,
  `product_name` VARCHAR(100) NOT NULL,
  `product_price` DECIMAL(12,2) NOT NULL,
  `vendor_id` INT NULL,
  `department_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_prod_vendor_id`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `Vendors` (`vendor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prod_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `Categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prod_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


/* Table `Customers` */

DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_id`));


/* Table `Purchases` */

DROP TABLE IF EXISTS `Purchases` ;

CREATE TABLE IF NOT EXISTS `Purchases` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `product_id` INT NULL,
  `units_bought` INT NOT NULL,
  `purchase_date` DATE NOT NULL,
  PRIMARY KEY (`purchase_id`),
  CONSTRAINT `fk_purch_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_purch_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


/* Table `Categories_Vendors` */

DROP TABLE IF EXISTS `Categories_Vendors` ;

CREATE TABLE IF NOT EXISTS `Categories_Vendors` (
  `category_vendor_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `vendor_id` INT NULL,
  PRIMARY KEY (`category_vendor_id`),
  CONSTRAINT `fk_cv_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `Categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cv_vendor_id`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `Vendors` (`vendor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* Create Table Complete */ 

insert into `Vendors` (`vendor_name`, `vendor_start_date`)
values 
("Kellogg's", '1941-05-01'),
('Best Groceries', '2022-10-01'),
('The Food People', '2021-12-14'),
('Blue Diamond', '1910-01-03'),
('Pfizer', '1974-03-08'),
('Quaker', '1877-06-08'),
('Kraft/Heinz', '1915-03-28'),
('Dole', '2021-10-07'),
('Chiquita', '2018-05-15');


insert into `Categories` (`category_name`)
values
('Milk'),
('Cereal'),
('Cheese'),
('Fruit'),
('Condiments'),
('Ibuprofen'),
('Snacks'),
('Breakfast');


insert into `Departments` (`department_name`)
values
('Dairy'),
('Produce'),
('Dry Goods'),
('Meat'),
('Fish'),
('Food Misc.'),
('Pharmacy'); 

insert into `Products` (`product_count`, `product_name`, `product_price`, `vendor_id`, `department_id`, `category_id`)
values
('30', 'Cheerios', '3.50', (select vendor_id from Vendors where vendor_name = "Kellogg's"), (select department_id from Departments where department_name = 'Dry Goods'), (select category_id from Categories where category_name = 'Cereal')), 
('10', 'Ketchup', '4.00', (select vendor_id from Vendors where vendor_name = "Kraft/Heinz"), (select department_id from Departments where department_name = 'Food Misc.'), (select category_id from Categories where category_name = 'Condiments')), 
('30', 'Fruit Loops', '3.00', (select vendor_id from Vendors where vendor_name = "Kellogg's"), (select department_id from Departments where department_name = 'Dry Goods'), (select category_id from Categories where category_name = 'Cereal')), 
('80', 'Advil (200 tablets)', '18.49', (select vendor_id from Vendors where vendor_name = "Pfizer"), (select department_id from Departments where department_name = 'Pharmacy'), (select category_id from Categories where category_name = 'Ibuprofen')), 
('12', 'Almond Milk (half gallon)', '3.38', (select vendor_id from Vendors where vendor_name = "Blue Diamond"), (select department_id from Departments where department_name = 'Dairy'), (select category_id from Categories where category_name = 'Milk')); 


insert into `Customers` (`customer_name`)
values
('Joey Tribbiani'),
('Chandler Bing'),
('Rachel Green'),
('Phoebe Buffay'), 
('Monica Geller'),
('Ross Geller');

insert into `Purchases` (`customer_id`, `product_id`, `units_bought`, `purchase_date`)
values
  ('3', '1', '2', '2024-01-06'),
  ('3', '4', '3', '2024-01-06'), 
  ('3', '2', '2', '2024-01-06'),
  ('5', '1', '1', '2024-01-14'),
  ('1', '3', '5', '2024-01-29'),
  ('1', '5', '4', '2024-01-29');


insert into `Categories_Vendors` (`category_id`, `vendor_id`)
values
('1', '4'),
('2', '1'),
('2', '6'),
('3', '7'), 
('4', '8'), 
('4', '9'),
('5', '7'), 
('6', '5'),
('7', '1'),
('8', '1');